print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love my sweetheart!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
#print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
print("I Love Hofstra!");
